# Prandi Alessandro

# Esercizio 1
Creare un notebook jupyter che a partire dal testo contenuto nel file ___"J_Verne_girodelmondoin80giorni.txt"___:

1. crei un dizionario delle frequenze per ciascun carattere (**line feed escluso**); 
2. crei il dizionario delle adiacenze per ciascun carattere (**line feed escluso**);
3. **[FACOLTATIVO]** crei un indice dei capitoli. Ogni capitolo inizia riportando il numero romano del capitolo e il suo titolo in questo modo:

>CAPITOLO XXIX.
>
>Nel quale si narrano cose che capitano unicamente sulle ferrovie
>americane.

In [12]:
char_freq = {}
with open("./J_Verne_girodelmondoin80giorni.txt") as file:
    f = file.readlines()
    for line in f:
        for char in line:
            if char != "\n":
                if char in char_freq:
                    char_freq[char] += 1
                else:
                    char_freq[char] = 1
                    
char_freq

{' ': 59718,
 'I': 916,
 'L': 498,
 'G': 590,
 'R': 169,
 'O': 231,
 'D': 231,
 'E': 532,
 'M': 422,
 'N': 329,
 'T': 189,
 'A': 632,
 'U': 145,
 'V': 157,
 'F': 1178,
 'S': 665,
 ',': 6381,
 '—': 896,
 '=': 2,
 'Q': 192,
 'u': 10152,
 'i': 32215,
 'n': 22842,
 'd': 11885,
 'c': 12687,
 'e': 36940,
 's': 18049,
 'm': 8352,
 'o': 29700,
 'g': 8240,
 'l': 20506,
 'a': 37759,
 '.': 4127,
 '_': 858,
 'p': 8380,
 'r': 21059,
 't': 19567,
 'è': 607,
 'v': 7140,
 'à': 526,
 '’': 1877,
 'C': 550,
 '1': 104,
 '9': 15,
 '4': 29,
 'P': 639,
 'q': 1741,
 'h': 3337,
 'b': 3738,
 '8': 33,
 '7': 28,
 '2': 73,
 '-': 311,
 'w': 116,
 'B': 250,
 'ì': 431,
 '[': 16,
 ']': 16,
 'ù': 349,
 'f': 3205,
 'z': 2363,
 'y': 254,
 'k': 181,
 'ò': 840,
 '?': 360,
 ';': 179,
 '!': 595,
 'J': 48,
 '“': 267,
 '„': 248,
 'é': 4,
 'H': 137,
 ':': 158,
 'K': 112,
 '(': 45,
 '3': 28,
 '5': 46,
 ')': 45,
 'È': 52,
 '0': 107,
 'Y': 83,
 '6': 14,
 'x': 291,
 '/': 2,
 'X': 57,
 'j': 42,
 'î': 1,
 'Z': 3,
 'ô': 8,
 'ê': 2,
 '

In [ ]:
diz_ad = {}

with open("./J_Verne_girodelmondoin80giorni.txt") as file:
    f = file.readlines() 

    for line in f:
        line = line.strip() 
        for i in range(len(line) - 1):  
            char = line[i]
            next_char = line[i + 1]
       
            if char and next_char:
                if char in diz_ad:
                    if next_char not in diz_ad[char]:
                        diz_ad[char].append(next_char)
                else:
                    diz_ad[char] = [next_char]

diz_ad



{'I': ['L',
  'R',
  'N',
  'O',
  'U',
  ' ',
  'T',
  't',
  'M',
  'n',
  'l',
  's',
  'I',
  '.',
  'v',
  'o',
  'V',
  'm',
  'X',
  'A',
  'C',
  '-',
  'r'],
 'G': ['I', 'a', 'r', 'i', 'l', 'u', 'o', 'h', 'N', 'H', 'R', 'e'],
 'R': ['O', 'N', 'A', 'E', 'I', 'e', 'u', 'i', 'a', 'o'],
 'O': [' ',
  'N',
  'T',
  'R',
  'L',
  '.',
  'v',
  'g',
  'r',
  'h',
  'n',
  't',
  'b',
  'y',
  'f',
  'c',
  'l',
  'M',
  'B',
  'm',
  'a'],
 ' ': ['D',
  'M',
  'O',
  'G',
  'V',
  'T',
  'E',
  'm',
  'p',
  'o',
  'è',
  'd',
  'e',
  'F',
  'l',
  't',
  'v',
  'i',
  'R',
  'C',
  '—',
  '1',
  'I',
  'P',
  'q',
  's',
  'a',
  'r',
  'c',
  'n',
  '7',
  'S',
  'B',
  '_',
  'u',
  'L',
  'f',
  'g',
  'b',
  'N',
  'A',
  'Q',
  'w',
  'U',
  'h',
  '2',
  'J',
  'H',
  '“',
  'K',
  '(',
  '3',
  'È',
  '5',
  'z',
  ' ',
  '„',
  'Y',
  '8',
  '9',
  '4',
  '6',
  'X',
  'Z',
  'y',
  'x',
  'W',
  'j',
  '.'],
 'D': ['E', 'O', 'I', 'i', 'e', '’', 'u', 'o', 'a'],
 'E': ['L',


In [26]:
with open("./J_Verne_girodelmondoin80giorni.txt") as file:
    f = file.readlines()
    for i,line in enumerate(f):
        if line.startswith("CAPITOLO"):
            print(line, end="")
            k = i + 2
            while f[k] != "\n":
                print(f[k], end="")
                k += 1
            print("")



CAPITOLO PRIMO.
Nel quale Phileas Fogg e Gambalesta si accettano reciprocamente l’uno
come padrone l’altro come servitore.

CAPITOLO II.
Nel quale Gambalesta è convinto d’aver finalmente trovato il suo ideale.

CAPITOLO III.
Nel quale s’impegna una conversazione che potrà costar caro a Phileas
Fogg.

CAPITOLO IV.
Nel quale Phileas Fogg sbalordisce Gambalesta, suo servo.

CAPITOLO V.
Nel quale un nuovo valore comparisce sulla piazza di Londra.

CAPITOLO VI.
Nel quale l’agente Fix mostra un’impazienza più che legittima.

CAPITOLO VII.
Che prova una volta di più l’inutilità dei passaporti in materia di
polizia.

CAPITOLO VIII.
Nel quale Gambalesta parla forse un po’ più del bisogno.

CAPITOLO IX.
Dove il mar Rosso e il mar delle Indie si mostrano propizii ai disegni
di Phileas Fogg.

CAPITOLO X.
Dove Gambalesta è felicissimo di non perdere che le scarpe.

CAPITOLO XI.
Dove Phileas Fogg compra a prezzo favoloso una cavalcatura.

CAPITOLO XII.
Nel quale Phileas Fogg e i suoi compagni si avv

# Esercizio 2
Dato `n`numero intero maggiore o uguale a 2 crea una matrice di numpy che abbia la struttura seguente esemplificata, per il caso `n=7`. 

`[[1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]]`
 

In [2]:
import numpy as np

In [ ]:
n = 7
matrice = 2 * np.ones(n**2, dtype=np.int32)
matrice[::2] = 1
matrice_new = matrice.reshape((n,n))
matrice_new

array([[1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1]])

# Esercizio 3
Crea un array unidimensionale di numpy lungo 21 elementi i cui valori sono 1,2 e 3 alernatici ciclicamente (`[1,2,3,1,2,3,.....]`).

In [32]:
dim = 21
array = np.ones(dim, np.int16)
array[1::3] = 2
array[2::3] = 3
array

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
      dtype=int16)